[package]
name = "loa"
version = "0.0.1"
published-at = "0x0b639fd79c62f27e3c6d46d30b1332933fa5e32d91ddf165c771caaacf524481"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "mainnet" }
multisig = {git = "https://github.com/hotrhino/Multisig.git", rev="master"}

[addresses]
loa =  "0x0"
Sui =  "0x2"
std =  "0x1"
